# LW_RandomWelcomeMessage
# 这是配置文件，请在此配置插件的各项功能。
# 可以加入QQ群：645921477，一起交流学习！
debug: false  # 调试模式（如有用）

# 消息系统配置
messages:
  # ==============================
  # 消息配置
  # ------------------------------
  # 配置格式
  # 权重:消息内容
  # 权重小于等于0时不显示消息
  # 权重可为任意数，但建议不要超过100
  # 可用变量（需启用对应消息源）：
  # {player}    - 触发事件的玩家名称
  # {hitokoto}  - 一言服务返回内容（未启用时回退本地消息）
  # {shici}     - 诗词服务返回内容（未启用时回退本地消息）
  # {shici_[type]}  - [type]为诗词类型（例：shici_shuqing，需在诗词服务配置中设定,未启用时回退本地消息，无分类时显示为全部诗词）
  # {random}    - 随机选择内容（根据权重分配）
  # ==============================
  mixed-format:
    - "40:&r“{shici}” 欢迎{player}进入服务器！"
    - "30:&r“{hitokoto}” 欢迎{player}进入服务器！" # 启用一言服务
    - "30:&r{shici}" # 仅启用诗词服务
    - "40:&r欢迎{player}进入服务器！" # 仅启用本地消息

  # 随机选择权重
  random-weight:
    shici: 50
    hitokoto: 50

  # =========================
  # ========================
  # 一言服务配置
  # ========================
  hitokoto:
    api-url: "https://international.v1.hitokoto.cn/"  # API端点地址
    timeout: 3000  # 请求超时时间（单位：毫秒）

  # ==============================
  # 诗词服务配置
  # ------------------------------
  # 分类接口地址（参考文档：https://v1.jinrishici.com/）
  # ==============================
  shici:
    all: "https://v1.jinrishici.com/all"
    timeout: 3000  # 请求超时时间（单位：毫秒）
    # 分类接口地址
    categories:
      shuqing: "https://v1.jinrishici.com/shuqing"

# =============================

# ==============================
# 节日模式配置（没做好，先不用）
# ------------------------------
# 日期格式：MM-DD:节日名称:诗词类型
# 启用后优先使用节日专属消息模板
# ==============================
festival:
  enable: true  # 启用节日模式

  # 节日消息模板（变量说明）：
  # {jieri_shici} - 节日专属诗词内容
  # {festival_name} - 节日显示名称
  mixed-format:
    - "“{jieri_shici}” {festival_name}快乐！"

  # 节日日期映射表
  dates:
    - "04-05:清明节:jieri/qingmingjie"  # 清明节配置
    - "01-22:春节:jieri/chunjie"       # 春节配置

# ==============================
# 音效配置
# ------------------------------
# 支持 Minecraft 原版音效类型：
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# ==============================
sound:
  enable: true                   # 启用音效
  type: ENTITY_PLAYER_LEVELUP    # 音效类型
  volume: 1.0                    # 音量（0.0-1.0）
  pitch: 1.0                     # 音调（0.5-2.0）

# ==============================
# 显示设置
# ==============================
settings:
  use-actionbar: true  # 使用动作栏显示消息（禁用时在聊天框显示）